/**
 * remark plugin: rewrites Markdown image references like
 *   ![alt](/images/photo.png)
 * into responsive `<img>` tags.
 *
 * In dev mode: emits the original PNG (served from public/images/).
 * In build mode: emits AVIF srcset (variants generated by CI + Worker).
 */
import { visit } from 'unist-util-visit';
import sizeOf from 'image-size';
import { existsSync, readFileSync } from 'node:fs';

const WIDTHS = [400, 800, 1200];

export function remarkResponsiveImages({ dev = false } = {}) {
  return (tree) => {
    let imageIndex = 0;

    visit(tree, 'image', (node) => {
      if (!node.url || !node.url.startsWith('/images/') || !node.url.endsWith('.png')) {
        return;
      }

      const base = node.url.replace(/\.png$/, '');
      const localPath = `./public${node.url}`;

      let naturalWidth, naturalHeight;
      try {
        if (existsSync(localPath)) {
          const dims = sizeOf(readFileSync(localPath));
          naturalWidth = dims.width;
          naturalHeight = dims.height;
        }
      } catch {
        /* validate-content reports the missing image */
      }

      const isFirst = imageIndex === 0;
      imageIndex++;

      node.data = node.data ?? {};

      if (dev) {
        node.data.hProperties = {
          src: node.url,
          sizes: '(max-width: 65ch) 100vw, 65ch',
          ...(naturalWidth && { width: naturalWidth }),
          ...(naturalHeight && { height: naturalHeight }),
          loading: isFirst ? 'eager' : 'lazy',
          decoding: 'async',
          fetchpriority: isFirst ? 'high' : 'auto',
          alt: node.alt ?? '',
        };
      } else {
        node.data.hProperties = {
          src: `${base}@800.avif`,
          srcset: WIDTHS.map(w => `${base}@${w}.avif ${w}w`).join(', '),
          sizes: '(max-width: 65ch) 100vw, 65ch',
          ...(naturalWidth && { width: naturalWidth }),
          ...(naturalHeight && { height: naturalHeight }),
          loading: isFirst ? 'eager' : 'lazy',
          decoding: isFirst ? 'sync' : 'async',
          fetchpriority: isFirst ? 'high' : 'low',
          alt: node.alt ?? '',
        };
      }
    });
  };
}

export default remarkResponsiveImages;
